[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python mongodb_connection.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/healthz"
healthcheckTimeout = 30
healthcheckInterval = 15

[service]
internal_port = 8080