[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python mongodb_connection.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 60

[service]
internal_port = 8080