[
build
]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[
deploy
]
startCommand = "python discord_bot1.py"
healthcheckPath = "/healthz"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[[
services
]]
name = "discordbot"